/*
 * Exchange Platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.hsrm.mi.swtp.exchangeplatform.model.rest_models;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Timeslot
 */
@JsonPropertyOrder({
  Timeslot.JSON_PROPERTY_ID,
  Timeslot.JSON_PROPERTY_ROOM,
  Timeslot.JSON_PROPERTY_DAY,
  Timeslot.JSON_PROPERTY_TIME_START,
  Timeslot.JSON_PROPERTY_TIME_END,
  Timeslot.JSON_PROPERTY_LECTURER,
  Timeslot.JSON_PROPERTY_CAPACITY,
  Timeslot.JSON_PROPERTY_POSSIBLE_TRADES,
  Timeslot.JSON_PROPERTY_ATTENDEES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-11-27T14:09:40.175837+01:00[Europe/Berlin]")
public class Timeslot {
  public static final String JSON_PROPERTY_ID = "id";
  private Long id;

  public static final String JSON_PROPERTY_ROOM = "room";
  private Room room;

  public static final String JSON_PROPERTY_DAY = "day";
  private DayEnum day;

  public static final String JSON_PROPERTY_TIME_START = "time_start";
  private java.sql.Timestamp timeStart;

  public static final String JSON_PROPERTY_TIME_END = "time_end";
  private java.sql.Timestamp timeEnd;

  public static final String JSON_PROPERTY_LECTURER = "lecturer";
  private Lecturer lecturer;

  public static final String JSON_PROPERTY_CAPACITY = "capacity";
  private Integer capacity;

  public static final String JSON_PROPERTY_POSSIBLE_TRADES = "possibleTrades";
  private List<TradeOffer> possibleTrades = null;

  public static final String JSON_PROPERTY_ATTENDEES = "attendees";
  private Integer attendees;


  public Timeslot id(Long id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getId() {
    return id;
  }


  public void setId(Long id) {
    this.id = id;
  }


  public Timeslot room(Room room) {
    
    this.room = room;
    return this;
  }

   /**
   * Get room
   * @return room
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ROOM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Room getRoom() {
    return room;
  }


  public void setRoom(Room room) {
    this.room = room;
  }


  public Timeslot day(DayEnum day) {
    
    this.day = day;
    return this;
  }

   /**
   * Get day
   * @return day
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_DAY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public DayEnum getDay() {
    return day;
  }


  public void setDay(DayEnum day) {
    this.day = day;
  }


  public Timeslot timeStart(java.sql.Timestamp timeStart) {
    
    this.timeStart = timeStart;
    return this;
  }

   /**
   * Get timeStart
   * @return timeStart
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TIME_START)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public java.sql.Timestamp getTimeStart() {
    return timeStart;
  }


  public void setTimeStart(java.sql.Timestamp timeStart) {
    this.timeStart = timeStart;
  }


  public Timeslot timeEnd(java.sql.Timestamp timeEnd) {
    
    this.timeEnd = timeEnd;
    return this;
  }

   /**
   * Get timeEnd
   * @return timeEnd
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_TIME_END)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public java.sql.Timestamp getTimeEnd() {
    return timeEnd;
  }


  public void setTimeEnd(java.sql.Timestamp timeEnd) {
    this.timeEnd = timeEnd;
  }


  public Timeslot lecturer(Lecturer lecturer) {
    
    this.lecturer = lecturer;
    return this;
  }

   /**
   * Get lecturer
   * @return lecturer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_LECTURER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Lecturer getLecturer() {
    return lecturer;
  }


  public void setLecturer(Lecturer lecturer) {
    this.lecturer = lecturer;
  }


  public Timeslot capacity(Integer capacity) {
    
    this.capacity = capacity;
    return this;
  }

   /**
   * Get capacity
   * @return capacity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_CAPACITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getCapacity() {
    return capacity;
  }


  public void setCapacity(Integer capacity) {
    this.capacity = capacity;
  }


  public Timeslot possibleTrades(List<TradeOffer> possibleTrades) {
    
    this.possibleTrades = possibleTrades;
    return this;
  }

  public Timeslot addPossibleTradesItem(TradeOffer possibleTradesItem) {
    if (this.possibleTrades == null) {
      this.possibleTrades = new ArrayList<>();
    }
    this.possibleTrades.add(possibleTradesItem);
    return this;
  }

   /**
   * Get possibleTrades
   * @return possibleTrades
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_POSSIBLE_TRADES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<TradeOffer> getPossibleTrades() {
    return possibleTrades;
  }


  public void setPossibleTrades(List<TradeOffer> possibleTrades) {
    this.possibleTrades = possibleTrades;
  }


  public Timeslot attendees(Integer attendees) {
    
    this.attendees = attendees;
    return this;
  }

   /**
   * Get attendees
   * @return attendees
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ATTENDEES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getAttendees() {
    return attendees;
  }


  public void setAttendees(Integer attendees) {
    this.attendees = attendees;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Timeslot timeslot = (Timeslot) o;
    return Objects.equals(this.id, timeslot.id) &&
        Objects.equals(this.room, timeslot.room) &&
        Objects.equals(this.day, timeslot.day) &&
        Objects.equals(this.timeStart, timeslot.timeStart) &&
        Objects.equals(this.timeEnd, timeslot.timeEnd) &&
        Objects.equals(this.lecturer, timeslot.lecturer) &&
        Objects.equals(this.capacity, timeslot.capacity) &&
        Objects.equals(this.possibleTrades, timeslot.possibleTrades) &&
        Objects.equals(this.attendees, timeslot.attendees);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, room, day, timeStart, timeEnd, lecturer, capacity, possibleTrades, attendees);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Timeslot {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    room: ").append(toIndentedString(room)).append("\n");
    sb.append("    day: ").append(toIndentedString(day)).append("\n");
    sb.append("    timeStart: ").append(toIndentedString(timeStart)).append("\n");
    sb.append("    timeEnd: ").append(toIndentedString(timeEnd)).append("\n");
    sb.append("    lecturer: ").append(toIndentedString(lecturer)).append("\n");
    sb.append("    capacity: ").append(toIndentedString(capacity)).append("\n");
    sb.append("    possibleTrades: ").append(toIndentedString(possibleTrades)).append("\n");
    sb.append("    attendees: ").append(toIndentedString(attendees)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

