/*
 * Exchange Platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.hsrm.mi.swtp.exchangeplatform.model.rest_models;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * TradeOffer
 */
@JsonPropertyOrder({
  TradeOffer.JSON_PROPERTY_OFFERED_TIMESLOT_ID,
  TradeOffer.JSON_PROPERTY_WANTED_TIMESLOT_ID,
  TradeOffer.JSON_PROPERTY_ID,
  TradeOffer.JSON_PROPERTY_INSTANT,
  TradeOffer.JSON_PROPERTY_COLLIDES
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-11-27T14:09:40.175837+01:00[Europe/Berlin]")
public class TradeOffer {
  public static final String JSON_PROPERTY_OFFERED_TIMESLOT_ID = "offeredTimeslotId";
  private Long offeredTimeslotId;

  public static final String JSON_PROPERTY_WANTED_TIMESLOT_ID = "wantedTimeslotId";
  private Long wantedTimeslotId;

  public static final String JSON_PROPERTY_ID = "id";
  private Integer id;

  public static final String JSON_PROPERTY_INSTANT = "instant";
  private Boolean instant;

  public static final String JSON_PROPERTY_COLLIDES = "collides";
  private Boolean collides;


  public TradeOffer offeredTimeslotId(Long offeredTimeslotId) {
    
    this.offeredTimeslotId = offeredTimeslotId;
    return this;
  }

   /**
   * Get offeredTimeslotId
   * @return offeredTimeslotId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_OFFERED_TIMESLOT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getOfferedTimeslotId() {
    return offeredTimeslotId;
  }


  public void setOfferedTimeslotId(Long offeredTimeslotId) {
    this.offeredTimeslotId = offeredTimeslotId;
  }


  public TradeOffer wantedTimeslotId(Long wantedTimeslotId) {
    
    this.wantedTimeslotId = wantedTimeslotId;
    return this;
  }

   /**
   * Get wantedTimeslotId
   * @return wantedTimeslotId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_WANTED_TIMESLOT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getWantedTimeslotId() {
    return wantedTimeslotId;
  }


  public void setWantedTimeslotId(Long wantedTimeslotId) {
    this.wantedTimeslotId = wantedTimeslotId;
  }


  public TradeOffer id(Integer id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getId() {
    return id;
  }


  public void setId(Integer id) {
    this.id = id;
  }


  public TradeOffer instant(Boolean instant) {
    
    this.instant = instant;
    return this;
  }

   /**
   * Get instant
   * @return instant
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_INSTANT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getInstant() {
    return instant;
  }


  public void setInstant(Boolean instant) {
    this.instant = instant;
  }


  public TradeOffer collides(Boolean collides) {
    
    this.collides = collides;
    return this;
  }

   /**
   * Get collides
   * @return collides
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_COLLIDES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getCollides() {
    return collides;
  }


  public void setCollides(Boolean collides) {
    this.collides = collides;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TradeOffer tradeOffer = (TradeOffer) o;
    return Objects.equals(this.offeredTimeslotId, tradeOffer.offeredTimeslotId) &&
        Objects.equals(this.wantedTimeslotId, tradeOffer.wantedTimeslotId) &&
        Objects.equals(this.id, tradeOffer.id) &&
        Objects.equals(this.instant, tradeOffer.instant) &&
        Objects.equals(this.collides, tradeOffer.collides);
  }

  @Override
  public int hashCode() {
    return Objects.hash(offeredTimeslotId, wantedTimeslotId, id, instant, collides);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TradeOffer {\n");
    sb.append("    offeredTimeslotId: ").append(toIndentedString(offeredTimeslotId)).append("\n");
    sb.append("    wantedTimeslotId: ").append(toIndentedString(wantedTimeslotId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    instant: ").append(toIndentedString(instant)).append("\n");
    sb.append("    collides: ").append(toIndentedString(collides)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

