/*
 * Exchange Platform API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package de.hsrm.mi.swtp.exchangeplatform.model.rest_models;

import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * TradeRequest
 */
@JsonPropertyOrder({
  TradeRequest.JSON_PROPERTY_OFFERED_TIMESLOT_ID,
  TradeRequest.JSON_PROPERTY_WANTED_TIMESLOT_ID,
  TradeRequest.JSON_PROPERTY_OFFERED_BY_STUDENT_MATRICULATION_NUMBER,
  TradeRequest.JSON_PROPERTY_FORCED,
  TradeRequest.JSON_PROPERTY_ADMIN_ID
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2019-11-27T14:09:40.175837+01:00[Europe/Berlin]")
public class TradeRequest {
  public static final String JSON_PROPERTY_OFFERED_TIMESLOT_ID = "offeredTimeslotId";
  private Long offeredTimeslotId;

  public static final String JSON_PROPERTY_WANTED_TIMESLOT_ID = "wantedTimeslotId";
  private Long wantedTimeslotId;

  public static final String JSON_PROPERTY_OFFERED_BY_STUDENT_MATRICULATION_NUMBER = "offeredByStudentMatriculationNumber";
  private Long offeredByStudentMatriculationNumber;

  public static final String JSON_PROPERTY_FORCED = "forced";
  private Boolean forced;

  public static final String JSON_PROPERTY_ADMIN_ID = "adminId";
  private Long adminId;


  public TradeRequest offeredTimeslotId(Long offeredTimeslotId) {
    
    this.offeredTimeslotId = offeredTimeslotId;
    return this;
  }

   /**
   * Get offeredTimeslotId
   * @return offeredTimeslotId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_OFFERED_TIMESLOT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getOfferedTimeslotId() {
    return offeredTimeslotId;
  }


  public void setOfferedTimeslotId(Long offeredTimeslotId) {
    this.offeredTimeslotId = offeredTimeslotId;
  }


  public TradeRequest wantedTimeslotId(Long wantedTimeslotId) {
    
    this.wantedTimeslotId = wantedTimeslotId;
    return this;
  }

   /**
   * Get wantedTimeslotId
   * @return wantedTimeslotId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_WANTED_TIMESLOT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getWantedTimeslotId() {
    return wantedTimeslotId;
  }


  public void setWantedTimeslotId(Long wantedTimeslotId) {
    this.wantedTimeslotId = wantedTimeslotId;
  }


  public TradeRequest offeredByStudentMatriculationNumber(Long offeredByStudentMatriculationNumber) {
    
    this.offeredByStudentMatriculationNumber = offeredByStudentMatriculationNumber;
    return this;
  }

   /**
   * Get offeredByStudentMatriculationNumber
   * @return offeredByStudentMatriculationNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_OFFERED_BY_STUDENT_MATRICULATION_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getOfferedByStudentMatriculationNumber() {
    return offeredByStudentMatriculationNumber;
  }


  public void setOfferedByStudentMatriculationNumber(Long offeredByStudentMatriculationNumber) {
    this.offeredByStudentMatriculationNumber = offeredByStudentMatriculationNumber;
  }


  public TradeRequest forced(Boolean forced) {
    
    this.forced = forced;
    return this;
  }

   /**
   * Get forced
   * @return forced
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_FORCED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getForced() {
    return forced;
  }


  public void setForced(Boolean forced) {
    this.forced = forced;
  }


  public TradeRequest adminId(Long adminId) {
    
    this.adminId = adminId;
    return this;
  }

   /**
   * Get adminId
   * @return adminId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")
  @JsonProperty(JSON_PROPERTY_ADMIN_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getAdminId() {
    return adminId;
  }


  public void setAdminId(Long adminId) {
    this.adminId = adminId;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TradeRequest tradeRequest = (TradeRequest) o;
    return Objects.equals(this.offeredTimeslotId, tradeRequest.offeredTimeslotId) &&
        Objects.equals(this.wantedTimeslotId, tradeRequest.wantedTimeslotId) &&
        Objects.equals(this.offeredByStudentMatriculationNumber, tradeRequest.offeredByStudentMatriculationNumber) &&
        Objects.equals(this.forced, tradeRequest.forced) &&
        Objects.equals(this.adminId, tradeRequest.adminId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(offeredTimeslotId, wantedTimeslotId, offeredByStudentMatriculationNumber, forced, adminId);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TradeRequest {\n");
    sb.append("    offeredTimeslotId: ").append(toIndentedString(offeredTimeslotId)).append("\n");
    sb.append("    wantedTimeslotId: ").append(toIndentedString(wantedTimeslotId)).append("\n");
    sb.append("    offeredByStudentMatriculationNumber: ").append(toIndentedString(offeredByStudentMatriculationNumber)).append("\n");
    sb.append("    forced: ").append(toIndentedString(forced)).append("\n");
    sb.append("    adminId: ").append(toIndentedString(adminId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

