package de.hsrm.mi.swtp.exchangeplatform.messaging.message;

public enum MessageType {
	ADD_TIMESLOT_WAITLIST_SUCCESS,
	ALL_MODULE_TIMESLOTS_FULL,
	EXCHANGEPLATFORM_STATUS,
	FORCED_TRADE_OFFER,
	JOIN_TIMESLOT_SUCCESS,
	LEAVE_MODULE_SUCCESS,
	LEAVE_TIMESLOT_SUCCESS,
	LOGIN,
	PO_CHANGED,
	PO_VIOLATION,
	PO_VIOLATION_CP,
	PO_VIOLATION_DUAL,
	PO_VIOLATION_PROGRESSIVE_REGULATION,
	PO_VIOLATION_SEMESTER,
	REMOVE_TIMESLOT_WAITLIST_SUCCESS,
	TRADE_OFFER_DENIED,
	TRADE_OFFER_SUCCESS,
	UPDATE_TIMESLOT,
	;
}
